import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const formatDateTime = (value) => {
  if (!value) return '';
  const d = new Date(value);
  if (Number.isNaN(d.getTime())) return String(value);
  return d.toLocaleString();
};

const renderComplaintReport = (doc, { complaint, history }) => {
  const title = 'Complaint Report with Status History';
  doc.setFontSize(14);
  doc.text(title, 105, 16, { align: 'center' });

  doc.setFontSize(9);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 105, 22, { align: 'center' });

  doc.setLineWidth(0.2);
  doc.line(10, 26, 200, 26);

  const complaintId = complaint?.comp_id ?? complaint?.complaint_id ?? '';
  const subject = complaint?.comp_subject ?? complaint?.subject ?? '';

  const headerText = `Complaint #${complaintId}: ${subject}`;
  doc.setFontSize(10);
  autoTable(doc, {
    startY: 32,
    head: [[headerText]],
    body: [],
    theme: 'grid',
    styles: { fontSize: 10, halign: 'left' },
    headStyles: { fillColor: [20, 84, 20], textColor: [255, 255, 255] },
    tableWidth: 'auto'
  });

  const details = [
    ['Client', complaint?.client_name ?? complaint?.client_info?.client_name ?? complaint?.client_info?.client_full_name ?? '-'],
    ['Location', complaint?.location_name ?? '-'],
    ['Equipment', Array.isArray(complaint?.equipments_used) ? complaint.equipments_used.join(', ') : (complaint?.equipments_used ?? complaint?.equipments ?? '-')],
    ['Assigned To', Array.isArray(complaint?.personnel_assigned)
      ? complaint.personnel_assigned.map((p) => p.user_name).filter(Boolean).join(', ')
      : (complaint?.assigned_personnel ?? '-')],
    ['Date', formatDateTime(complaint?.comp_date ?? complaint?.complaint_date ?? complaint?.comp_date_created ?? complaint?.date_created)],
    ['Current Status', complaint?.latest_status ?? complaint?.comp_status ?? complaint?.current_status ?? '-']
  ];

  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 6,
    body: details,
    theme: 'plain',
    styles: { fontSize: 10, cellPadding: 1.5 },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 35 },
      1: { cellWidth: 150 }
    }
  });

  doc.setFontSize(11);
  doc.text('Status History', 12, doc.lastAutoTable.finalY + 10);

  const rows = Array.isArray(history)
    ? history.map((h) => [
        formatDateTime(h.history_date),
        h.status_name || '-',
        h.updated_by_name || '-'
      ])
    : [];

  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 12,
    head: [['History Date', 'Status', 'Updated By']],
    body: rows,
    theme: 'striped',
    styles: { fontSize: 9 },
    headStyles: { fillColor: [240, 240, 240], textColor: [0, 0, 0] }
  });

  doc.setFontSize(9);
  doc.text('Report generated by GSD Reservation System', 105, 290, { align: 'center' });
};

export const generateComplaintReportPdf = ({ complaint, history, items, fileName } = {}) => {
  const list = Array.isArray(items)
    ? items
    : (complaint ? [{ complaint, history }] : []);

  if (list.length === 0) return;

  const doc = new jsPDF('p', 'mm', 'a4');
  list.forEach((item, idx) => {
    if (idx > 0) doc.addPage();
    renderComplaintReport(doc, item);
  });

  const firstComplaintId = list[0]?.complaint?.comp_id ?? list[0]?.complaint?.complaint_id ?? '';
  const defaultName = list.length === 1
    ? `Complaint_${firstComplaintId}_Report.pdf`
    : 'Complaint_Reports.pdf';

  doc.save(fileName || defaultName);
};
